openapi: 3.0.0
info:
  title: Expense Tracker API
  description: A simple API to track you expenses.
components:
  schemas:
    expense:
      $ref: "./schemas/expense.yaml"
paths:
  /expenses/:
    $ref: "./paths/expenses.yaml"
  /expenses/{id}/:
    $ref: "./paths/expenses-detail.yaml"
