# Generated by Django 6.0.1 on 2026-01-24 16:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(default='New Folder', help_text='Name of the node')),
                ('type', models.CharField(choices=[('folder', 'Folder'), ('dataset', 'Dataset')], help_text='Node type: folder for organization, dataset for actual data', max_length=20)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent node in the hierarchy. Null for root nodes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web_gis_app.datasetnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the dataset content and purpose')),
                ('type', models.CharField(choices=[('vector', 'Vector'), ('raster', 'Raster'), ('text', 'Text')], help_text='Dataset type: vector, raster, geo_pdf, or document', max_length=20)),
                ('format', models.CharField(choices=[('geojson', 'Geojson'), ('shapefile', 'Shapefile'), ('kml', 'Kml'), ('gpkg', 'Geopackage'), ('geotiff', 'Geotiff'), ('cog', 'Cog'), ('png', 'Png'), ('jpeg', 'Jpeg'), ('pdf', 'Pdf'), ('txt', 'Txt')], help_text='File format: geojson, shapefile, geotiff, etc.', max_length=20)),
                ('file_name', models.CharField(help_text='Primary file name', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='Primary file size in bytes')),
                ('cloud_storage_path', models.CharField(help_text='Cloud storage path for the primary file', max_length=500)),
                ('files', models.JSONField(blank=True, default=list, help_text='Additional files for multi-file formats (shapefiles, etc.)')),
                ('srid', models.IntegerField(blank=True, help_text='Spatial Reference System ID (EPSG code)', null=True)),
                ('bbox', models.JSONField(blank=True, help_text='Bounding box [minx, miny, maxx, maxy]', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional format-specific metadata (resolution, bands, CRS details, etc.)')),
                ('dataset_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='web_gis_app.datasetnode')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='DatasetClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depth', models.IntegerField(help_text='Distance between ancestor and descendant (0 for self-reference)')),
                ('ancestor', models.ForeignKey(help_text='Ancestor node in the hierarchy', on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_closures', to='web_gis_app.datasetnode')),
                ('descendant', models.ForeignKey(help_text='Descendant node in the hierarchy', on_delete=django.db.models.deletion.CASCADE, related_name='descendant_closures', to='web_gis_app.datasetnode')),
            ],
            options={
                'unique_together': {('ancestor', 'descendant')},
            },
        ),
    ]
