# Generated by Django 6.0.1 on 2026-01-22 16:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import web_gis_app.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('folder', 'Folder'), ('dataset', 'Dataset')], help_text='Node type: folder for organization, dataset for actual data', max_length=20)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent node in the hierarchy. Null for root nodes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web_gis_app.datasetnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name of the dataset', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the dataset content and purpose')),
                ('type', models.CharField(choices=web_gis_app.constants.DatasetType.choices, help_text='Dataset type: vector, raster, geo_pdf, or document', max_length=20)),
                ('format', models.CharField(choices=[('geojson', 'Geojson'), ('shapefile', 'Shapefile'), ('kml', 'Kml'), ('gpkg', 'Geopackage'), ('geotiff', 'Geotiff'), ('cog', 'Cog'), ('png', 'Png'), ('jpeg', 'Jpeg'), ('pdf', 'Pdf')], help_text='File format: geojson, shapefile, geotiff, etc.', max_length=20)),
                ('cloud_storage_path', models.CharField(help_text='Cloud storage path. File path for single-file formats, directory path for multi-file formats (e.g., shapefiles)', max_length=500)),
                ('srid', models.IntegerField(blank=True, help_text='Spatial Reference System ID (EPSG code)', null=True)),
                ('bbox', models.JSONField(blank=True, help_text='Bounding box [minx, miny, maxx, maxy]', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional format-specific metadata (resolution, bands, CRS details, etc.)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('dataset_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dataset', to='web_gis_app.datasetnode')),
            ],
            options={
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
                'db_table': 'dataset',
            },
        ),
        migrations.CreateModel(
            name='DatasetFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_storage_path', models.CharField(help_text='Full cloud storage path to this specific file', max_length=500)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('role', models.CharField(default='main', help_text="File role: 'main' for primary file, or specific roles like 'index', 'attributes', 'projection' for shapefiles", max_length=50)),
                ('dataset', models.ForeignKey(help_text='Parent dataset this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='web_gis_app.dataset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset File',
                'verbose_name_plural': 'Dataset Files',
                'db_table': 'dataset_file',
                'unique_together': {('dataset', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DatasetClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depth', models.IntegerField(help_text='Distance between ancestor and descendant (0 for self-reference)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('ancestor', models.ForeignKey(help_text='Ancestor node in the hierarchy', on_delete=django.db.models.deletion.CASCADE, to='web_gis_app.datasetnode')),
                ('descendant', models.ForeignKey(help_text='Descendant node in the hierarchy', on_delete=django.db.models.deletion.CASCADE, related_name='descendant_closures', to='web_gis_app.datasetnode')),
            ],
            options={
                'unique_together': {('ancestor', 'descendant')},
            },
        ),
    ]
