# Generated by Django 6.0.1 on 2026-01-23 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_gis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetclosure',
            name='ancestor',
            field=models.ForeignKey(help_text='Ancestor node in the hierarchy', on_delete=django.db.models.deletion.CASCADE, related_name='ancestor_closures', to='web_gis_app.datasetnode'),
        ),
    ]
