# Generated by Django 6.0.1 on 2026-02-07 08:38

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_gis_app', '0004_remove_dataset_bbox_remove_dataset_srid_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='style',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(help_text='PostGIS geometry (Point, LineString, Polygon, etc.).', srid=4326)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='Feature properties from the GeoJSON.')),
                ('dataset', models.ForeignKey(help_text='The dataset this feature belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='web_gis_app.dataset')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'feature',
                'indexes': [models.Index(fields=['dataset'], name='feature_dataset_ffe856_idx')],
            },
        ),
    ]
