# Generated by Django 6.0.1 on 2026-02-17 18:47

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_gis_app", "0005_alter_layer_style_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="TileSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current processing status of the tileset.",
                        max_length=20,
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cloud storage path for the processed tile-ready file.",
                        max_length=500,
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="Size of the processed file in bytes."
                    ),
                ),
                (
                    "min_zoom",
                    models.IntegerField(
                        default=0, help_text="Minimum zoom level for tile serving."
                    ),
                ),
                (
                    "max_zoom",
                    models.IntegerField(
                        default=22, help_text="Maximum zoom level for tile serving."
                    ),
                ),
                (
                    "bounds",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Geographic bounds [west, south, east, north] in EPSG:4326.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if processing failed.",
                    ),
                ),
                (
                    "dataset",
                    models.OneToOneField(
                        help_text="Source dataset this tileset was generated from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tileset",
                        to="web_gis_app.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tile Set",
                "verbose_name_plural": "Tile Sets",
                "db_table": "tileset",
            },
        ),
    ]
