# Generated by Django 6.0.1 on 2026-02-18 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_gis_app", "0006_tileset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="layer",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web_gis_app.dataset"
            ),
        ),
    ]
