# Generated by Django 6.0.1 on 2026-02-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_gis_app", "0010_remove_raster_dem_dataset_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataset",
            name="format",
            field=models.CharField(
                choices=[
                    ("shapefile", "Shapefile"),
                    ("kml", "Kml"),
                    ("gpkg", "Geopackage"),
                    ("geotiff", "Geotiff"),
                    ("cog", "Cog"),
                    ("png", "Png"),
                    ("jpeg", "Jpeg"),
                    ("pdf", "Pdf"),
                    ("txt", "Txt"),
                ],
                help_text="File format: shapefile, geotiff, etc.",
                max_length=20,
            ),
        ),
    ]
