apiVersion: v1
data:
  config.json: |
    {
      "identities": [
        {
          "name": "backend-app",
          "credentials": [
            {
              "accessKey": "EEQb7fnFvvDsoHdr3qZh",
              "secretKey": "PpuxU5kwQkt6mkqrde3k"
            }
          ],
          "actions": [
            "Admin",
            "Read",
            "Write"
          ]
        }
      ]
    }
  security.toml: |
    [cors.allowed_origins]
    values = "https://worldofapps.bar,https://app.worldofapps.bar,http://localhost:3000,http://127.0.0.1:3000,http://localhost:5173,http://127.0.0.1:5173"
kind: ConfigMap
metadata:
  name: seaweedfs-s3-config
