# Generated by Django 5.1.1 on 2025-11-19 10:38

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce_app",
            "0003_alter_category_options_remove_product_currency_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user",
            new_name="added_by",
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=9),
        ),
    ]
