# Generated by Django 5.1.1 on 2025-11-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce_app",
            "0005_rename_quantity_product_stock_remove_cart_products_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="cart_items",
            new_name="items",
        ),
    ]
