# Generated by Django 5.1.1 on 2024-11-02 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shared", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="shared.basemodel",
                    ),
                ),
                ("description", models.TextField()),
            ],
            bases=("shared.basemodel",),
        ),
    ]
