# Generated by Django 5.1.1 on 2025-06-27 09:55

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(srid=4326),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="map_app.layer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeatureAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("date", "Date"),
                            ("datetime", "DateTime"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("numeric_value", models.FloatField(blank=True, null=True)),
                ("date_value", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="map_app.feature",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key", "value"], name="map_app_fea_key_cb3d10_idx"
                    ),
                    models.Index(
                        fields=["key", "numeric_value"],
                        name="map_app_fea_key_6c3073_idx",
                    ),
                    models.Index(
                        fields=["key", "date_value"], name="map_app_fea_key_d62f66_idx"
                    ),
                    models.Index(
                        fields=["feature", "key"], name="map_app_fea_feature_3e9c0a_idx"
                    ),
                ],
                "unique_together": {("feature", "key")},
            },
        ),
    ]
