# Generated by Django 5.1.1 on 2025-06-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="file_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="layer",
            name="file_size",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="layer",
            name="geometry_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="layer",
            name="srid",
            field=models.IntegerField(default=4326),
        ),
    ]
