apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  DB_NAME: cG9zdGdyZXM=  # postgres (base64 encoded)
  DB_USER: cG9zdGdyZXM=  # postgres (base64 encoded)
  DB_PASSWORD: cG9zdGdyZXM=  # postgres (base64 encoded)
