# Generated by Django 6.0.1 on 2026-02-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="app_name",
            field=models.CharField(
                choices=[("web_gis_app", "Web Gis"), ("backend_projects", "Main")],
                max_length=100,
            ),
        ),
    ]
