# Generated by Django 5.1.1 on 2025-02-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_markdown_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
