# Generated by Django 5.1.1 on 2025-02-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_markdown_app', '0003_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.FileField(null=True, upload_to='notes/'),
        ),
    ]
