openapi: 3.0.0
info:
  title: Note Markdown App API
  description: API documentation for Note Markdown application
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /notes/:
    $ref: "paths/notes.yaml"
  /notes/{id}/:
    $ref: "paths/notes-detail.yaml"
  /notes/{id}/markdown-preview/:
    $ref: "paths/markdown-preview.yaml"
