# Generated by Django 6.0.1 on 2026-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_manager", "0003_alter_chatsession_llm"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("assistant", "Assistant")],
                default="user",
                max_length=20,
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                ],
                default="complete",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
