version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: expense
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U expense_user -d expense"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  web:
    build: .
    command: gunicorn expense_tracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
