openapi: 3.0.0
info:
  title: Expense Tracker API
  description: A simple API to track you expenses.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /expenses/:
    $ref: "./paths/expenses.yaml"
  /expenses/{id}/:
    $ref: "./paths/expenses-detail.yaml"
