name: Django CI # Workflow name.
on: # Events.
  push:
    branches: [ "todo*" ]

jobs: # Workflow definition.
  
  test: # Job for running tests.
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./todo_project
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4  # Github's pre-defined actions.
    
    # Reuse Python environment from build job
    - name: Set up Python ${{ matrix.python-version }} 
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Run Tests
    - name: Run Tests
      run: |
        python manage.py test

  build: 
    runs-on: ubuntu-latest 
    needs: test
    defaults:
      run:
        working-directory: ./todo_project
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4  # Github's pre-defined actions.
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PERSONAL_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-projects:todo .
  
      # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-projects:todo